title: Taher Chegini
author: Taher Chegini
copyright: "2022"
logo: images/me.png

execute:
  execute_notebooks: off

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/cheginit/personal_website
  path_to_book: personal_website
  branch: main

html:
  use_repository_button: true