name: gh-pages
channels:
  - conda-forge
  - nodefaults
dependencies:
  - click
  - docutils
  - jsonschema
  - jupytext
  - linkify-it-py
  - myst-nb
  - pyyaml
  - sphinx
  - sphinx-comments
  - sphinx-copybutton
  - sphinx-external-toc
  - sphinx-panels
  - sphinx-thebe
  - sphinx-book-theme
  - sphinx-togglebutton
  - sphinxcontrib-bibtex

  # dev deps
  - codespell
  - psutil
  - pytest
  - pytest-clarity
  - pytest-sugar
  - pytest-xdist

  # IDE deps
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - nb_black

  - pip
  - pip:
    - jupyter-book
    - ghp-import
    - nbmake

